//
//  BobInteractor.swift
//  ModuleB
//
//  Created by admin on 25/09/2019.
//  Copyright (c) 2019 admin. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class BobInteractor {
  var delegate: ((String) -> Void)? = nil {
    didSet {
      print("Interactor delegate was set!")
    }
  }
}

// MARK: - Extensions -

extension BobInteractor: BobInteractorInterface {
  func done(text: String) {
    self.delegate?(text)
  }
}
