//
//  BobInterfaces.swift
//  ModuleB
//
//  Created by admin on 25/09/2019.
//  Copyright (c) 2019 admin. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol BobWireframeInterface: class {
}

protocol BobViewInterface: class {
}

protocol BobPresenterInterface: class {
  var previousResult: String { get }
  func textEntered(_: String?)
  func doneButtonPushed()
}

public protocol BobInteractorInterface: class {
  func done(text: String)
}
