//
//  BobPresenter.swift
//  ModuleB
//
//  Created by admin on 25/09/2019.
//  Copyright (c) 2019 admin. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class BobPresenter {
  
  // MARK: - Private properties -
  
  private unowned let view: BobViewInterface
  private let interactor: BobInteractorInterface
  private let wireframe: BobWireframeInterface
  let previousResult: String
  
  var userEnteredText: String?
  
  // MARK: - Lifecycle -
  
  init(view: BobViewInterface, interactor: BobInteractorInterface, wireframe: BobWireframeInterface, previousResult: String) {
    self.view = view
    self.interactor = interactor
    self.wireframe = wireframe
    self.previousResult = previousResult
  }
}

// MARK: - Extensions -

extension BobPresenter: BobPresenterInterface {
  func textEntered(_ text: String?) {
    self.userEnteredText = text
  }
  
  func doneButtonPushed() {
    let text = self.userEnteredText ?? ""
    self.interactor.done(text: text)
  }
}
