//
//  BobViewController.swift
//  ModuleB
//
//  Created by admin on 25/09/2019.
//  Copyright (c) 2019 admin. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class BobViewController: UIViewController {
  
  static let identifier = "Bob"
  
  // MARK: - Public properties -
  
  var presenter: BobPresenterInterface!
  
  // MARK: - Lifecycle -
  
  override func viewDidLoad() {
    super.viewDidLoad()
    self.previousResultLabel.text = presenter.previousResult
  }
  
  @IBOutlet weak var previousResultLabel: UILabel!
  
  @IBAction func textEntered(_ sender: UITextField) {
    presenter.textEntered(sender.text)
  }
  
  @IBAction func doneButtonPushed(_ sender: Any) {
    presenter.doneButtonPushed()
  }
}

// MARK: - Extensions -

extension BobViewController: BobViewInterface {
}
