//
//  BobWireframe.swift
//  ModuleB
//
//  Created by admin on 25/09/2019.
//  Copyright (c) 2019 admin. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import ModuleKit

final class BobWireframe<ViewControllerPresenter: RouterProtocol>
where ViewControllerPresenter.Presentable == UIViewController {
  
  // MARK: - Private properties -
  
  private let storyboard = UIStoryboard(name: "Bob", bundle: Bundle(for: BobViewController.self))
  
  // MARK: - Module setup -
  
  init(interactor: BobInteractorInterface, viewControllerPresenter: ViewControllerPresenter, previousResult: String) {
    let moduleViewController = storyboard.instantiateViewController(withIdentifier: BobViewController.identifier) as! BobViewController
    
    let presenter = BobPresenter(view: moduleViewController, interactor: interactor, wireframe: self, previousResult: previousResult)
    moduleViewController.presenter = presenter
    viewControllerPresenter.present(moduleViewController)
  }
  
}

// MARK: - Extensions -

extension BobWireframe: BobWireframeInterface {
}
